name: Release 
on:
  push:
    branches:
      - master
jobs:
  release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Create Tag + Bump Version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: major
        CUSTOM_TAG: Beta-1.4
      id: tag_version
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "changelog.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}

