name: Release 
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Tag + Bump Version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: Beta-${{ steps.tag_version.outputs.new_tag }}
        custom_release_rules: "Release: Beta"
        release_branches: master
      id: tag_version
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "changelog.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}

